<?php

// Include the ThumbWhere SDK
require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'dependencies' . DIRECTORY_SEPARATOR . 'tw' . DIRECTORY_SEPARATOR . 'sdk.class.php');

/**
 * @file
 * Module for the ThumbWhere Producer Entity
 *
 */

if(!isset($_SESSION['thumbwhere_thumbwhere_producer'])) {
  $_SESSION['thumbwhere_thumbwhere_producer'] = array();

  // Simulatation of unique external ids...
  $_SESSION['thumbwhere_thumbwhere_producer']['id'] = 100000;
}

/**
 * Implement hook_entity_info().
 *
 * We define two entities here - the actual entity that will hold our domain
 * specific information and an entity that holds information about the different
 * types of entities. See here: http://drupal.org/node/977380 for a discussion on this
 * choice.
 */
function thumbwhere_producer_entity_info() {
  $return['thumbwhere_producer'] = array(

    // The human-readable name of the type.
    'label' => t('ThumbWhereProducer'),

    // (used by DrupalDefaultEntityController) The name of the entity type's base table.
    'base table' => 'thumbwhere_producer',

    // fieldable: Set to TRUE if you want your entity type to accept fields being attached to it.
    'fieldable' => TRUE,

    'entity keys' => array(
        'id' => 'thumbwhere_producer_id',
    ),

    // A function taking an entity and an entity type as arguments and returning the label of the entity.
    // The entity label is the main string associated with an entity; for example, the title of a node or
    // the subject of a comment. If there is an entity object property that defines the label, use the
    // 'label' element of the 'entity keys' return value component to provide this information (see below).
    // If more complex logic is needed to determine the label of an entity, you can instead specify a callback
    // function here, which will be called to determine the entity label. See also the entity_label()
    // function, which implements this logic.
    'label callback' => 'entity_class_label',

    // A function taking an entity as argument and returning the uri elements of the entity, e.g. 'path' and 'options'.
    // The actual entity uri can be constructed by passing these elements to url().
    'uri callback' => 'entity_class_uri',

    //
    // Entity API Components
    //

    // The module whwre we can find our classes
    'module' => 'thumbwhere_producer',

    // The entity class and controller class extend the classes provided by the Entity API
    'entity class' => 'ThumbWhereProducer',

    // Which Entity API contoller
    'controller class' => 'ThumbWhereProducerController',

    // The information below is used by the ThumbWhereProducerUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/content/thumbwhere_producers',
      'file' => 'thumbwhere_producer.admin.inc',
      'controller class' => 'ThumbWhereProducerUIController',
      'menu wildcard' => '%thumbwhere_producer',
    ),
  );

  return $return;
}


/**
 * Implements hook_permission().
 */
function thumbwhere_producer_permission() {

  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer thumbwhere_producers' => array(
      'title' => t('Administer thumbwhere_producers'),
      'description' => t('Edit and delete all thumbwhere_producers'),
    ),
  );

  return $permissions;
}


/**
 * Determines whether the given user has access to a thumbwhere_producer.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $thumbwhere_producer
 *   Optionally a thumbwhere_producer or a thumbwhere_producer type to check access for. If nothing is
 *   given, access for all thumbwhere_producers is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function thumbwhere_producer_access($op, $thumbwhere_producer = NULL, $account = NULL) {

  //if (user_access('administer thumbwhere_producers', $account)) {
  //  return TRUE;
 // }

  //return FALSE;
  return TRUE;
}




/**
 * Fetch a thumbwhere_producer object. Make sure that the wildcard you choose
 * in the thumbwhere_producer entity definition fits the function name here.
 *
 * @param $thumbwhere_producer_id
 *   Integer specifying the thumbwhere_producer id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $thumbwhere_producer object or FALSE if it cannot be loaded.
 *
 * @see thumbwhere_producer_load_multiple()
 */
function thumbwhere_producer_load($thumbwhere_producer_id, $reset = FALSE) {

  //

  $thumbwhere_producers = entity_load('thumbwhere_producer', array($thumbwhere_producer_id), array(), $reset);

  return reset($thumbwhere_producers);
}





/**
 * Load multiple thumbwhere_producers based on certain conditions.
 *
 * @param $thumbwhere_producer_ids
 *   An array of thumbwhere_producer IDs.
 * @param $conditions
 *   An array of conditions to match against the {thumbwhere_producer} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of thumbwhere_producer objects, indexed by thumbwhere_producer_id.
 *
 * @see entity_load()
 * @see thumbwhere_producer_load()
 */
/*
function thumbwhere_producer_load_multiple($thumbwhere_producer_ids = array(), $conditions = array(), $reset = FALSE) {



  $loaded = entity_load('thumbwhere_producer', $thumbwhere_producer_ids, $conditions, $reset);

  return $loaded;
}
*/

/**
 * Deletes a thumbwhere_producer.
 */
function thumbwhere_producer_delete(ThumbWhereProducer $thumbwhere_producer) {

  $thumbwhere_producer->delete();
}


/**
 * Delete multiple thumbwhere_producers.
 *
 * @param $thumbwhere_producer_ids
 *   An array of thumbwhere_producer IDs.
 */
/*
function thumbwhere_producer_delete_multiple(array $thumbwhere_producer_ids) {



  entity_get_controller('thumbwhere_producer')->delete($thumbwhere_producer_ids);
}
*/

/**
 * Create a thumbwhere_producer object.
 */
function thumbwhere_producer_create($values = array()) {

  return entity_get_controller('thumbwhere_producer')->create($values);
}


/**
 * Saves a thumbwhere_producer to the database.
 *
 * @param $thumbwhere_producer
 *   The thumbwhere_producer object.
 */
/*
function thumbwhere_producer_save(ThumbWhereProducer $thumbwhere_producer) {



  return $thumbwhere_producer->save();
}*/



/**
 * Insert a thumbwhere_producer
 *
 * @param $thumbwhere_producer
 *   The thumbwhere_producer object.
 */
/*
function thumbwhere_producer_insert(array $values = array()) {



  //return $thumbwhere_producer->create($values);
  return entity_get_controller('thumbwhere_producer')->insert($values);
}
*/






/**
 * URI callback for thumbwhere_producers
 */
function thumbwhere_producer_uri(ThumbWhereProducer $thumbwhere_producer) {



  return array(
    'path' => 'thumbwhere_producer/' . $thumbwhere_producer->thumbwhere_producer_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function thumbwhere_producer_page_title(ThumbWhereProducer $thumbwhere_producer) {



  return $thumbwhere_producer->name;
}


/**
 * Sets up content to show an individual thumbwhere_producer
 * @todo - get rid of drupal_set_title();
 */
function thumbwhere_producer_page_view($thumbwhere_producer, $view_mode = 'full') {



  $controller = entity_get_controller('thumbwhere_producer');
  $content = $controller->view(array($thumbwhere_producer->thumbwhere_producer_id => $thumbwhere_producer));
  drupal_set_title($thumbwhere_producer->name);
  return $content;
}


/**
 * Implements hook_views_api().
 */
function thumbwhere_producer_views_api() {



  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'thumbwhere_producer') . '/views',
  );
}


/**
 * Implement hook_theme().
 */
function thumbwhere_producer_theme() {



  return array(
    'thumbwhere_producer_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'thumbwhere_producer.admin.inc',
    ),
    'thumbwhere_producer' => array(
      'render element' => 'elements',
      'template' => 'thumbwhere_producer',
    )
  );
}


/**
 * Implements hook_menu_local_tasks_alter().
 */
function thumbwhere_producer_menu_local_tasks_alter(&$data, $router_item, $root_path) {

  // Add action link 'admin/structure/thumbwhere_producers/add' on 'admin/structure/thumbwhere_producers'.
  if ($root_path == 'admin/content/thumbwhere_producers') {
    $item = menu_get_item('admin/content/thumbwhere_producers/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * The class used for thumbwhere_producer entities
 */
class ThumbWhereProducer extends Entity {

  public function __construct($values = array()) {
    parent::__construct($values, 'thumbwhere_producer');
  }

  protected function defaultLabel() {
    return $this->name;
  }

  protected function defaultUri() {
    return array('path' => 'thumbwhere_producer/' . $this->thumbwhere_producer_id);
  }


}



/**
 * The Controller for ThumbWhereProducer entities
 */
class ThumbWhereProducerController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a thumbwhere_producer - we first set up the values that are specific
   * to our thumbwhere_producer schema but then also go through the EntityAPIController
   * function.
   *
   * @param $type
   *   The machine-readable type of the thumbwhere_producer.
   *
   * @return
   *   A thumbwhere_producer object with all default fields initialized.
   */
  /*
  public function create(array $values = array()) {



    //$values += array(
    //  'thumbwhere_id' => -1,
    //);

    return parent::create($values);
  }
  */


  /**
  * view
  * to our thumbwhere_producer schema but then also go through the EntityAPIController
  * function.
  *
  * @param $type
  *   The machine-readable type of the thumbwhere_producer.
  *
  * @return
  *   A thumbwhere_producer object with all default fields initialized.
  */
  /*
  public function view($entities, $view_mode = 'full', $langcode = NULL, $page = NULL) {



    $view = parent::view($entities, $view_mode, $langcode, $page);

    return $view;
  }
  */




  /**
  * query - Builds and executes the query for loading.
  *
  * @param $ids
  *   Array of ids
  *
  * @param $conditions
  *
  *
  *
  * @return
  *   A thumbwhere_producer object with all default fields initialized.
  */
  /*
  public function load($ids = array(), $conditions = array()) {



    $result = parent::load($ids, $conditions);

    //$result[1]->token = "my token";

    return $result;
  }
  */

  /**
  * Invoke
  *
  * @param $ids
  *   Array of ids
  *
  * @param $transaction
  *   If not null then the transaction this is taking part in
  *
  * @return
  *   A thumbwhere_producer object with all default fields initialized.
  */
  /*
  public function invoke($hook, $entity) {



    parent::invoke($hook, $entity);

  }
  */


  /**
  * Delete a thumbwhere_producer.
  *
  * @param $ids
  *   Array of ids
  *
  * @param $transaction
  *   If not null then the transaction this is taking part in
  *
  * @return
  *   A thumbwhere_producer object with all default fields initialized.
  */
  /*
  public function delete($ids, DatabaseTransaction $transaction = NULL) {



    parent::delete($ids, $transaction);

  }
  */


  /**
  * Save a thumbwhere_producer.
  *
  * @param $thumbwhere_producer
  *   The thumbwhere_producer being saved
  *
  * @param $transaction
  *   If not null then the transaction this is taking part in
  *
  * @return
  *   A thumbwhere_producer object with all default fields initialized.
  */
  /*
  public function save($thumbwhere_producer, DatabaseTransaction $transaction = NULL) {



    return parent::save($thumbwhere_producer, $transaction);
  }
  */


  /**
  * resetCache - Called when the cache is
  *
  * @param $ids
  *   Array of ids
  *
  * @return
  *   void
  */
  /*
  public function resetCache(array $ids = NULL) {



    parent::resetCache($ids);
  }
  */


  /**
  * query - Builds and executes the query for loading.
  *
  * @param $ids
  *   Array of ids
  *
  * @param $conditions
  *
  * @param $revision_id
  *
  *
  * @return
  *   A thumbwhere_producer object with all default fields initialized.
  */
  /*
  public function query($ids, $conditions, $revision_id = FALSE) {



    $result= parent::query($ids, $conditions, $revision_id);

    return $result;
  }
  */


  /**
   * Overriding the buldContent function to add entity specific fields
   */
  /*
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {

    $content = parent::buildContent($entity, $view_mode, $langcode, $content);

    $content['thumbwhere_producer_sample_data'] =  array(
      '#markup' => theme('thumbwhere_producer_sample_data', array('thumbwhere_producer_sample_data' => check_plain($entity->data['sample_data']), 'thumbwhere_producer' => $entity)),
    );

    return $content;
  }*/
}


/**
 * Implements hook_field_storage_load().
 *
 * Load field from storage
 *
 * @todo This needs to be improved
 */
/*
function thumbwhere_producer_field_storage_load($entity_type, $entities, $age, $fields, $options) {


}
*/



/**
* Implements hook_entity_presave().
*
* Act on an entity before it is about to be created or updated.
*
* @param $entity
*   The entity object
* @param $entity_type
*   The type of entity being saved (i.e. node, user, comment).
*/
function thumbwhere_producer_entity_presave($entity, $entity_type) {

  // We only look after what we want...
  if ($entity_type == 'thumbwhere_producer')  {



    // If this is new
    if ($entity->is_new)
    {
      // .. then we create a new thumbwhere_producer entity...

      twd('Creating Remote Object and linking to ThumbWhere entity..');

      // Link it up to the thumbwhere id
      $entity->pk_producer = $_SESSION['thumbwhere_thumbwhere_producer']['id']++;

    }
    else
    {
        // .. otherwise we calculate the changes and ship them off to thumbwhere
        twd('Calculate changes and ship them off to ThumbWhere');
    }
  }
}


/**
 * Implements thumbwhere_producer_entity_insert().
 *
 * Act on entities when inserted.
 *
 * @param $entity
 *   The entity object
 * @param $type
 *   The type of entity being inserted (i.e. node, user, comment).
 */
function thumbwhere_producer_entity_insert($entity, $type) {

  // Flee if this is not the entity type we are looking for
  if ($type != 'thumbwhere_producer') return;


}


/**
* Implements thumbwhere_producer_entity_delete().
*
* Act on entities when inserted.
*
* @param $entity
*   The entity object
* @param $type
*   The type of entity being deleted (i.e. node, user, comment).
*/
function thumbwhere_producer_entity_delete($entity, $type) {

  // Flee if this is not the entity type we are looking for
  if ($type != 'thumbwhere_producer') return;


}



