<?php

// Include the ThumbWhere SDK
require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'dependencies' . DIRECTORY_SEPARATOR . 'tw' . DIRECTORY_SEPARATOR . 'sdk.class.php');

/**
 * @file
 *
 * Main ThumbWhere Module file
 *
 * Core module functionality is here.
 *
 */

/**
 * Debug the calling function and it's paramaters to the log
 *
 * @see SimpletestUnitTestExampleTestCase.
 */
function twfd($dumpcallstack = FALSE) {
/*
  $bt = debug_backtrace();

  if (!module_exists('devel_debug_log')) {
    debug(date('Y-m-d\TH:i:s ') . 'FUNCTION' . $bt[1]['function']);
    debug(date('Y-m-d\TH:i:s ') . 'ARGS' . $bt[1]['args']);

    if ($dumpcallstack) {
      debug(date('Y-m-d\TH:i:s ') . 'CALLSTACK' . $bt);
    }
  }
  else {

    dd($bt[1]['function'], $label = date('Y-m-d\TH:i:s ') . 'FUNCTION');
    dd($bt[1]['args'], $label = date('Y-m-d\TH:i:s ') . 'ARGS');

    if ($dumpcallstack) {
      dd($bt, $label = date('Y-m-d\TH:i:s ') . 'CALLSTACK');
    }
  }
 */
}


/**
 * Print a message to the debug log
 */
function twCanDebug() {

  return (variable_get('thumbwhere_api_log_debug',0) == 1);

}

/**
 * Print a trace message to the debug log
 */
function twCanTrace() {

  return (variable_get('thumbwhere_api_log_trace',0) == 1);
}

/**
 * Print a message to the debug log
 */
function twCanInfo() {
  return (variable_get('thumbwhere_api_log_info',1) == 1);
}



/**
 * Print a message to the debug log
 *
 * @see SimpletestUnitTestExampleTestCase.
 */
function twd($massage) {

  if (!module_exists('devel_debug_log')) {
    debug(date('Y-m-d\TH:i:s ') . 'DEBUG ' . $massag);
    return;
  }

  dd($massage, $label = date('Y-m-d\TH:i:s ') . 'DEBUG ');

}

/**
 * A simple self-contained function used to demonstrate unit tests.
 *
 * @see SimpletestUnitTestExampleTestCase.
 */
function thumbwhere_feature_xyz($date_string) {
  if (empty($date_string) || $date_string == '0000-00-00' || $date_string == '0000-00-00 00:00:00') {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_help().
 */
function thumbwhere_help($section) {

  switch ($section) {
  case 'thumbwhere/reference':
    return '<p>' . t('This is a list of defined user functions that generated this current request lifecycle. Click on a function name to view its documention.') . '</p>';
  case 'thumbwhere/session':
    return '<p>' . t('Here are the contents of your <code>$_SESSION</code> variable.') . '</p>';
  case 'thumbwhere/variable':
    $api = variable_get('thumbwhere_api_url', 'api.drupal.org');
    return '<p>'
        . t(
            'This is a list of the variables and their values currently stored in variables table and the <code>$conf</code> array of your settings.php file. These variables are usually accessed with <a href="@variable-get-doc">variable_get()</a> and <a href="@variable-set-doc">variable_set()</a>. Variables that are too long can slow down your pages.',
            array(
                '@variable-get-doc' => "http://$api/api/HEAD/function/variable_get",
                '@variable-set-doc' => "http://$api/api/HEAD/function/variable_set"
            )) . '</p>';
  case 'thumbwhere/reinstall':
    return t('Warning - will delete your module tables and variables.');

  case 'admin/settings/modules#description':
    return t('Thumbwhere settings description.');
    break;

  case 'admin/help#thumbwhere':
    $output = '<p>'
        . t(
            'The ThumbWhere Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus mi ut risus fringilla a posuere quam feugiat. Mauris interdum, dui at eleifend rutrum, lacus risus aliquet arcu, ut eleifend magna augue a ligula. Nam accumsan suscipit volutpat. Suspendisse ut eros tempus purus suscipit placerat. Cras sed ipsum ligula. Pellentesque enim ligula, vehicula et fringilla eget, tincidunt vel magna. Nullam arcu sapien, interdum et pharetra at, ultrices nec nisi. Vivamus eleifend sollicitudin ligula, non auctor urna tincidunt sed.')
        . "</p>\n";
    $output .= '<p>'
        . t(
            'This module provides donec vitae risus ut nulla tristique cursus at ac arcu. Aliquam blandit feugiat posuere. Mauris vitae nisi quam. Aliquam fermentum orci sit amet risus sollicitudin id dapibus libero varius. Integer id rhoncus purus. Phasellus vel accumsan quam. Sed ornare malesuada ipsum in interdum. Praesent mauris nisl, laoreet iaculis blandit ut, faucibus ut libero. Maecenas molestie nibh at lectus luctus lacinia. Pellentesque tempor fermentum turpis et pharetra. Aenean lacinia nunc non lorem sollicitudin sit amet facilisis odio luctus. Aenean in orci vel augue sagittis commodo. In hac habitasse platea dictumst.')
        . "</p>\n";
    return $output;

  }
}

/**
 * Implements hook_modules_installed().
 *
 * @see thumbwhere_install()
 */
function thumbwhere_modules_installed($modules) {

  /*
  if (in_array('menu', $modules)) {
    $menu = array(
      'menu_name' => 'thumbwhere',
      'title' => t('thumbwhere'),
      'description' => t('thumbwhere link'),
    );
    menu_save($menu);
  }
   */
}

/**
 * Implements hook_menu().
 */
function thumbwhere_menu() {

  $items['admin/thumbwhere'] = array(
      'title' => 'ThumbWhere',
      'description' => 'Find and manage ThumbWhere entities.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('node_admin_content'),
      'access arguments' => array('access content overview'),
      'weight' => -10,
      'file' => 'thumbwhere_entity.admin.inc',
  );


  //
  // Config sections
  //

  $items['admin/config/thumbwhere/settings'] = array(
      'title' => 'ThumbWhere Settings',
      'description' => 'ThumbWhere configuration.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
          'thumbwhere_admin_settings'
      ),
      'access arguments' => array(
          'administer site configuration'
      ),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'thumbwhere.admin.inc',
  );

  $items['admin/config/thumbwhere'] = array(
      'title' => 'Thumbwhere Configuration',
      'description' => 'ThumbWhere configuration',
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
          'thumbwhere_admin_settings'
      ),
      'file' => 'thumbwhere.admin.inc',
      'access arguments' => array(
          'administer site configuration'
      ),
  );

  //
  // Report
  //

  $items['admin/reports/thumbwhere/activity'] = array(
      'title' => 'ThumbWhere Activity Report',
      'description' => 'View ThumbWhere Actvity.',
      'page arguments' => array(
          'thumbwhere_activity_report'
      ),
      'page callback' => 'thumbwhere_report_page',
      'access arguments' => array(
          'access thumbwhere report information'
      ),
  );

  $items['admin/reports/thumbwhere'] = array(
      'title' => 'ThumbWhere Reports',
      'description' => 'ThumbWhere general reports and dashboard.',
      'page callback' => 'thumbwhere_report_page',
      'page arguments' => array(
          'thumbwhere_summary_report'
      ),
      'access arguments' => array(
          'access thumbwhere report information'
      ),
  );

  return $items;
}

/**
 * Displays the debug messages table.
 */
function thumbwhere_report_page() {
  // Add auto-refresh javascript on the first page only.
  //if (!isset($_GET['page'])) {
  //  drupal_add_js(drupal_get_path('module', 'thumbwhere') . '/thumbwhere_report.js.js');
  //}

  $table_page = array(
      'messages_table' => devel_debug_log_get_messages_table(),
      'pager' => array(
          '#theme' => 'pager',
      ),
  );

  return $table_page;
}

/**
 * Implements hook_admin_paths().
 */
function thumbwhere_admin_paths() {
  $paths = array(
      'thumbwhere/*' => TRUE
  );
  return $paths;
}

/**
 * Implements hook_permission().
 */
function thumbwhere_permission() {
  return array(
      'access thumbwhere information' => array(
          'description' => t('View developer output like variable printouts, query log, etc.'),
          'title' => t('Access developer information'),
          'restrict access' => TRUE,
      ),
      'switch thumbwhere users' => array(
          'title' => t('Switch users'),
          'description' => t('Become any ThumbWhere user on the site with just a click.'),
          'restrict access' => TRUE,
      ),
      'send thumbwhere notifications' => array(
          'title' => t('Send ThumbWhere Notifications'),
          'description' => t('Allow the caller to call the Notifications Endpoint.'),
          'restrict access' => TRUE,
      ),
  );
}

/**
 * Implements hook_field_info().
 */
function thumbwhere_field_info() {
  return array(
      'thumbwhere_id' => array(
          'label' => t('ThumbWhere ID'),
          'description' => t('A ThumbWhere ID'),
          'instance_settings' => array(
              'text_processing' => FALSE
          ),
          'default_value' => array(
              0 => array(
                  'value' => '0',
              ),
          ),
          'default_widget' => 'thumbwhere_id_widget',
          'default_formatter' => 'thumbwhere_id_formatter',
      ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function thumbwhere_field_formatter_info() {
  return array(
      'thumbwhere_id_formatter' => array(
          'label' => t('ThumbWhere Entity ID Formatter'),
          'field types' => array(
              'thumbwhere_id'
          ),
      ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function thumbwhere_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
  case 'thumbwhere_id_formatter':
    foreach ($items as $delta => $item) {
      if ($item['thumbwhere_id']) {

        $formattedDate = $item['thumbwhere_id'];
        $element[$delta]['#markup'] = '<span>' . $formattedDate . '</span>';
      }
    }
    break;
  }
  return $element;
}

/**
 * Implements hook_field_widget_form().
 */
function thumbwhere_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $field_name = $field['field_name'];
  $field_type = $field['type'];

  $default_date_int = $instance['default_value'][0][$field_type][$field_type];

  if (isset($items[0]['thumbwhere_id'])) {
    $default_date_int = $items[0]['thumbwhere_id'];
  }

  switch ($instance['widget']['type']) {
  case 'thumbwhere_id':
    $element['thumbwhere_id'] = array(
        '#type' => 'textfield',
        '#title' => check_plain($element['#title']),
        '#description' => check_plain($element['#description']),
        '#default_value' => t($default_date_int),
        '#required' => $element['#required'],
        '#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
        '#delta' => $delta,
    //'#element_validate' => array('validateThumbWhereId'),
    );

    break;
  }
  return $element;
}

/**
 * Utility function which validates that the thumbwhere id is correct.
 */
/*
function validateThumbWhereId($element, &$form_state) {

  debug('validateThumbWhereId');
  debug($element);

  if (isset($element['#value'])) {
    $value = $element['#value'];

    if (!is_numeric($value))
    {
      form_set_error($element['#parents'][0], t($element['#title'] . ' must be an integer.'));
    }
  }
}
 */

/**
 * Implements hook_field_widget_error().
 */
function thumbwhere_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
  case 'thumbwhere_id_invalid':
    form_error($element, $error['message']);
    break;
  }
}

/**
 * Implements hook_field_is_empty().
 */
function thumbwhere_field_is_empty($item, $field) {
  if (empty($item['thumbwhere_id'])) {
    return TRUE;
  }
}

/**
 * Implements hook_field_widget_info().
 */
function thumbwhere_field_widget_info() {
  return array(
      'thumbwhere_id' => array(
          'label' => t('ThumbWhere Entity Id'),
          'field types' => array(
              'thumbwhere_id'
          ),
      ),
  );
}

/**
* Implements hook_cron().
*/
function thumbwhere_cron() {
   if (twCanDebug()) debug('thumbwhere_cron');
}





