<?php


/**
* @file
 * Install file ThumbWhere Module
 *
 * Everything that the module needs to do on instalation is performed here.
 *
 * @see http://drupal.org/node/707832
 * @see http://drupal.org/node/443536
 * @see field
 */

ddl('thumbwhere.module');

/**
 * Implementation of hook_help().
 */
function thumbwhere_help($section) {
  
  ddl('thumbwhere_help(' + $section + ')');
  
  switch ($section) {
    case 'thumbwhere/reference':
      return '<p>' . t('This is a list of defined user functions that generated this current request lifecycle. Click on a function name to view its documention.') . '</p>';
    case 'thumbwhere/session':
      return '<p>' . t('Here are the contents of your <code>$_SESSION</code> variable.') . '</p>';
    case 'thumbwhere/variable':
      $api = variable_get('thumbwhere_api_url', 'api.drupal.org');
      return '<p>' . t('This is a list of the variables and their values currently stored in variables table and the <code>$conf</code> array of your settings.php file. These variables are usually accessed with <a href="@variable-get-doc">variable_get()</a> and <a href="@variable-set-doc">variable_set()</a>. Variables that are too long can slow down your pages.', array('@variable-get-doc' => "http://$api/api/HEAD/function/variable_get", '@variable-set-doc' => "http://$api/api/HEAD/function/variable_set")) . '</p>';
    case 'thumbwhere/reinstall':
      return t('Warning - will delete your module tables and variables.');
      
      case 'admin/settings/modules#description':
        return t('Thumbwhere settings description.');
        break;
      
      case 'admin/help#thumbwhere':
        $output  = '<p>' . t('The ThumbWhere Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus mi ut risus fringilla a posuere quam feugiat. Mauris interdum, dui at eleifend rutrum, lacus risus aliquet arcu, ut eleifend magna augue a ligula. Nam accumsan suscipit volutpat. Suspendisse ut eros tempus purus suscipit placerat. Cras sed ipsum ligula. Pellentesque enim ligula, vehicula et fringilla eget, tincidunt vel magna. Nullam arcu sapien, interdum et pharetra at, ultrices nec nisi. Vivamus eleifend sollicitudin ligula, non auctor urna tincidunt sed.') . "</p>\n";
        $output .= '<p>' . t('This module provides donec vitae risus ut nulla tristique cursus at ac arcu. Aliquam blandit feugiat posuere. Mauris vitae nisi quam. Aliquam fermentum orci sit amet risus sollicitudin id dapibus libero varius. Integer id rhoncus purus. Phasellus vel accumsan quam. Sed ornare malesuada ipsum in interdum. Praesent mauris nisl, laoreet iaculis blandit ut, faucibus ut libero. Maecenas molestie nibh at lectus luctus lacinia. Pellentesque tempor fermentum turpis et pharetra. Aenean lacinia nunc non lorem sollicitudin sit amet facilisis odio luctus. Aenean in orci vel augue sagittis commodo. In hac habitasse platea dictumst.') . "</p>\n";
        return $output;
      
  }
}

/**
 * Implements hook_modules_installed().
 *
 * @see thumbwhere_install()
 */
function thumbwhere_modules_installed($modules) {
  
  ddl('thumbwhere_modules_installed(' + $modules + ')');
  
  if (in_array('menu', $modules)) {
    $menu = array(
      'menu_name' => 'thumbwhere',
      'title' => t('thumbwhere'),
      'description' => t('thumbwhere link'),
    );
    menu_save($menu);
  }
}

/**
 * Implements hook_menu().
 */
function thumbwhere_menu() {

  
  $items['admin/config/thumbwhere/settings'] = array(
    'title' => 'ThumbWhere Settings',
    'description' => 'ThumbWhere configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('thumbwhere_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'thumbwhere.admin.inc',
  );
  
  
  $items['admin/config/thumbwhere'] = array(
    'title' => 'Thumbwhere Configuration',
    'description' =>  'ThumbWhere configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('thumbwhere_admin_settings'),
    'file' => 'thumbwhere.admin.inc',
    'access arguments' => array('administer site configuration'),
  );
  
  
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function thumbwhere_admin_paths() {
  $paths = array(
    'thumbwhere/*' => TRUE
  );
  return $paths;
}


/**
* Implement hook_permission().
*/
function thumbwhere_permission() {
  return array(
    'access thumbwhere information' => array(
      'description' => t('View developer output like variable printouts, query log, etc.'),
      'title' => t('Access developer information'),
      'restrict access' => TRUE,
  ),
    'switch thumbwhere users' => array(
      'title' => t('Switch users'),
      'description' => t('Become any ThumbWhere user on the site with just a click.'),
      'restrict access' => TRUE,
  ),
  );
}


