<?php

// Include the ThumbWhere SDK
require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'dependencies' . DIRECTORY_SEPARATOR . 'tw' . DIRECTORY_SEPARATOR . 'sdk.class.php');

/**
 * @file
 * Module for the ThumbWhere Producer Entity
 *
 */

if(!isset($_SESSION['thumbwhere_producer'])) {
  $_SESSION['thumbwhere_producer'] = array();

  // Simulatation of unique external ids...
  $_SESSION['thumbwhere_producer']['id'] = 100000;
}

/**
 * Implement hook_entity_info().
 *
 * We define two entities here - the actual entity that will hold our domain
 * specific information and an entity that holds information about the different
 * types of entities. See here: http://drupal.org/node/977380 for a discussion on this
 * choice.
 */
function producer_entity_info() {
  $return['producer'] = array(

    // The human-readable name of the type.
    'label' => t('Producer'),

    // (used by DrupalDefaultEntityController) The name of the entity type's base table.
    'base table' => 'producer',

    // fieldable: Set to TRUE if you want your entity type to accept fields being attached to it.
    'fieldable' => TRUE,

    'entity keys' => array(
        'id' => 'producer_id',
    ),

    // A function taking an entity and an entity type as arguments and returning the label of the entity.
    // The entity label is the main string associated with an entity; for example, the title of a node or
    // the subject of a comment. If there is an entity object property that defines the label, use the
    // 'label' element of the 'entity keys' return value component to provide this information (see below).
    // If more complex logic is needed to determine the label of an entity, you can instead specify a callback
    // function here, which will be called to determine the entity label. See also the entity_label()
    // function, which implements this logic.
    'label callback' => 'entity_class_label',

    // A function taking an entity as argument and returning the uri elements of the entity, e.g. 'path' and 'options'.
    // The actual entity uri can be constructed by passing these elements to url().
    'uri callback' => 'entity_class_uri',

    //
    // Entity API Components
    //

    // The module whwre we can find our classes
    'module' => 'producer',

    // The entity class and controller class extend the classes provided by the Entity API
    'entity class' => 'Producer',

    // Which Entity API contoller
    'controller class' => 'ProducerController',

    // The information below is used by the ProducerUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/content/producers',
      'file' => 'producer.admin.inc',
      'controller class' => 'ProducerUIController',
      'menu wildcard' => '%producer',
    ),
  );

  return $return;
}


/**
 * Implements hook_permission().
 */
function producer_permission() {

  //dd('producer_permission');

  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer producers' => array(
      'title' => t('Administer producers'),
      'description' => t('Edit and delete all producers'),
    ),
  );

  return $permissions;
}


/**
 * Determines whether the given user has access to a producer.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $producer
 *   Optionally a producer or a producer type to check access for. If nothing is
 *   given, access for all producers is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function producer_access($op, $producer = NULL, $account = NULL) {

  if (user_access('administer producers', $account)) {
    return TRUE;
  }

  return FALSE;
}




/**
 * Fetch a producer object. Make sure that the wildcard you choose
 * in the producer entity definition fits the function name here.
 *
 * @param $producer_id
 *   Integer specifying the producer id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $producer object or FALSE if it cannot be loaded.
 *
 * @see producer_load_multiple()
 */
function producer_load($producer_id, $reset = FALSE) {

  //twfd();

  $producers = entity_load('producer', array($producer_id), array(), $reset);

  return reset($producers);
}





/**
 * Load multiple producers based on certain conditions.
 *
 * @param $producer_ids
 *   An array of producer IDs.
 * @param $conditions
 *   An array of conditions to match against the {producer} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of producer objects, indexed by producer_id.
 *
 * @see entity_load()
 * @see producer_load()
 */
/*
function producer_load_multiple($producer_ids = array(), $conditions = array(), $reset = FALSE) {

  twfd();

  $loaded = entity_load('producer', $producer_ids, $conditions, $reset);

  return $loaded;
}
*/

/**
 * Deletes a producer.
 */
function producer_delete(Producer $producer) {

  twfd();

  $producer->delete();
}


/**
 * Delete multiple producers.
 *
 * @param $producer_ids
 *   An array of producer IDs.
 */
/*
function producer_delete_multiple(array $producer_ids) {

  twfd();

  entity_get_controller('producer')->delete($producer_ids);
}
*/

/**
 * Create a producer object.
 */
function producer_create($values = array()) {

  twfd();

  return entity_get_controller('producer')->create($values);
}


/**
 * Saves a producer to the database.
 *
 * @param $producer
 *   The producer object.
 */
/*
function producer_save(Producer $producer) {

  twfd();

  return $producer->save();
}*/



/**
 * Insert a producer
 *
 * @param $producer
 *   The producer object.
 */
/*
function producer_insert(array $values = array()) {

  twfd();

  //return $producer->create($values);
  return entity_get_controller('producer')->insert($values);
}
*/






/**
 * URI callback for producers
 */
function producer_uri(Producer $producer) {

  twfd();

  return array(
    'path' => 'producer/' . $producer->producer_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function producer_page_title(Producer $producer) {

  twfd();

  return $producer->name;
}


/**
 * Sets up content to show an individual producer
 * @todo - get rid of drupal_set_title();
 */
function producer_page_view($producer, $view_mode = 'full') {

  twfd();

  $controller = entity_get_controller('producer');
  $content = $controller->view(array($producer->producer_id => $producer));
  drupal_set_title($producer->name);
  return $content;
}


/**
 * Implements hook_views_api().
 */
function producer_views_api() {

  twfd();

  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'producer') . '/views',
  );
}


/**
 * Implement hook_theme().
 */
function producer_theme() {

  twfd();

  return array(
    'producer_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'producer.admin.inc',
    ),
    'producer' => array(
      'render element' => 'elements',
      'template' => 'producer',
    )
  );
}


/**
 * Implements hook_menu_local_tasks_alter().
 */
function producer_menu_local_tasks_alter(&$data, $router_item, $root_path) {

  // Add action link 'admin/structure/producers/add' on 'admin/structure/producers'.
  if ($root_path == 'admin/content/producers') {
    $item = menu_get_item('admin/content/producers/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * The class used for producer entities
 */
class Producer extends Entity {

  public function __construct($values = array()) {
    parent::__construct($values, 'producer');
  }

  protected function defaultLabel() {
    return $this->name;
  }

  protected function defaultUri() {
    return array('path' => 'producer/' . $this->producer_id);
  }


}



/**
 * The Controller for Producer entities
 */
class ProducerController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a producer - we first set up the values that are specific
   * to our producer schema but then also go through the EntityAPIController
   * function.
   *
   * @param $type
   *   The machine-readable type of the producer.
   *
   * @return
   *   A producer object with all default fields initialized.
   */
  /*
  public function create(array $values = array()) {

    twfd();

    //$values += array(
    //  'thumbwhere_id' => -1,
    //);

    return parent::create($values);
  }
  */


  /**
  * view
  * to our producer schema but then also go through the EntityAPIController
  * function.
  *
  * @param $type
  *   The machine-readable type of the producer.
  *
  * @return
  *   A producer object with all default fields initialized.
  */
  /*
  public function view($entities, $view_mode = 'full', $langcode = NULL, $page = NULL) {

    twfd();

    $view = parent::view($entities, $view_mode, $langcode, $page);

    return $view;
  }
  */




  /**
  * query - Builds and executes the query for loading.
  *
  * @param $ids
  *   Array of ids
  *
  * @param $conditions
  *
  *
  *
  * @return
  *   A producer object with all default fields initialized.
  */
  /*
  public function load($ids = array(), $conditions = array()) {

    twfd();

    $result = parent::load($ids, $conditions);

    //$result[1]->token = "my token";

    //dd($result);

    return $result;
  }
  */

  /**
  * Invoke
  *
  * @param $ids
  *   Array of ids
  *
  * @param $transaction
  *   If not null then the transaction this is taking part in
  *
  * @return
  *   A producer object with all default fields initialized.
  */
  /*
  public function invoke($hook, $entity) {

    twfd();

    parent::invoke($hook, $entity);

  }
  */


  /**
  * Delete a producer.
  *
  * @param $ids
  *   Array of ids
  *
  * @param $transaction
  *   If not null then the transaction this is taking part in
  *
  * @return
  *   A producer object with all default fields initialized.
  */
  /*
  public function delete($ids, DatabaseTransaction $transaction = NULL) {

    twfd();

    parent::delete($ids, $transaction);

  }
  */


  /**
  * Save a producer.
  *
  * @param $producer
  *   The producer being saved
  *
  * @param $transaction
  *   If not null then the transaction this is taking part in
  *
  * @return
  *   A producer object with all default fields initialized.
  */
  /*
  public function save($producer, DatabaseTransaction $transaction = NULL) {

    twfd();

    return parent::save($producer, $transaction);
  }
  */


  /**
  * resetCache - Called when the cache is
  *
  * @param $ids
  *   Array of ids
  *
  * @return
  *   void
  */
  /*
  public function resetCache(array $ids = NULL) {

    twfd();

    parent::resetCache($ids);
  }
  */


  /**
  * query - Builds and executes the query for loading.
  *
  * @param $ids
  *   Array of ids
  *
  * @param $conditions
  *
  * @param $revision_id
  *
  *
  * @return
  *   A producer object with all default fields initialized.
  */
  /*
  public function query($ids, $conditions, $revision_id = FALSE) {

    twfd();

    $result= parent::query($ids, $conditions, $revision_id);

    return $result;
  }
  */


  /**
   * Overriding the buldContent function to add entity specific fields
   */
  /*
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {

    $content = parent::buildContent($entity, $view_mode, $langcode, $content);

    $content['producer_sample_data'] =  array(
      '#markup' => theme('producer_sample_data', array('producer_sample_data' => check_plain($entity->data['sample_data']), 'producer' => $entity)),
    );

    return $content;
  }*/
}


/**
 * Implements hook_field_storage_load().
 *
 * Load field from storage
 *
 * @todo This needs to be improved
 */
/*
function producer_field_storage_load($entity_type, $entities, $age, $fields, $options) {

    twfd();
}
*/



/**
* Implements hook_entity_presave().
*
* Act on an entity before it is about to be created or updated.
*
* @param $entity
*   The entity object
* @param $type
*   The type of entity being saved (i.e. node, user, comment).
*/
function producer_entity_presave($entity, $type) {

  // Flee if this is not the entity type we are looking for
  //if ($type != 'producer') return;




  twfd();

  $entity->thumbwhere_id = 100;

}


/**
 * Implements producer_entity_insert().
 *
 * Act on entities when inserted.
 *
 * @param $entity
 *   The entity object
 * @param $type
 *   The type of entity being inserted (i.e. node, user, comment).
 */
function producer_entity_insert($entity, $type) {

  // Flee if this is not the entity type we are looking for
  if ($type != 'producer') return;

  twfd();
}


/**
* Implements producer_entity_delete().
*
* Act on entities when inserted.
*
* @param $entity
*   The entity object
* @param $type
*   The type of entity being deleted (i.e. node, user, comment).
*/
function producer_entity_delete($entity, $type) {

  // Flee if this is not the entity type we are looking for
  if ($type != 'producer') return;

  twfd();
}



